### ISSUE TITLE
Error when trying to login to CIMC

### ISSUE THREAD

**Issue by wipeoutstu** [CiscoDevNet/esxi-auto-installer#26]
Im getting the below errors when trying to run the autoinstall process:

2021-11-21 23:37:25 PST [INFO] Starting ESXi hypervisor installation using custom ISO URL: http://10.10.10.254/custom-iso/10.10.10.10_1637566640.5050092.iso
2021-11-21 23:37:25 PST [INFO] Connecting to CIMC IP: 10.10.10.10 using account: admin
2021-11-21 23:37:25 PST [ERROR] Error when trying to login to CIMC: "urlopen error [SSL] internal error (_ssl.c:1131)"

Hardware connecting to:
6248 FI's, 5108 Chassis, B200 m3 Blades, 3.1(1e) firmware

**Comment by mikeslowik** [comment]
Hi,

This error is coming from IMC SDK, which Auto Installer uses to login to CIMC and mount the ISO. It clearly failed on an attempt to login to the blade although I have no idea what the exact root cause was here as I never got this "SSL internal error" when testing it. 

I was going to suggest connecting with CIMC IP 10.10.10.10:80 which should force http instead of https, however I have just checked and it seems there is a bug in IMC SDK, as it still tries to use secure connection and throws this error:

ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108) 

I'll see if I can workaround this and force non-secure connection to CIMC when port 80 is provided, as I would really like to see if Auto Installer works on your M3 blades.

Side remark: have you considered updating firmware on those blades? I doubt this is the root cause but having them on slightly less "mature" firmware does not seem to be a bad idea ;)

**Comment by wipeoutstu** [comment]
Hi,
Thank you so much for looking at this, yeah i tried forcing port 80 in case it was a https issue, but i got the same message (as you say likely due to the sdk bug.)

I do have plans to upgrade the firmware, it's a lab environment which i have been using to train break-fix engineers on UCS, and the next part of the training (I've Done Theory, Practical install from UCS to OS, Troubleshooting, Physical install & cabling) is going to be the firmware updates. I'll be completing several smaller firmware updates so i can go through the process with the break-fix engineers who want to transition into professional Services.

I did wonder if the issue could be related to the geriatric firmware :)
I would be very interested to see if you can find a workaround, but if not, i'll keep testing in-between the firmware updates and let you know what the magic FW version is :)

**Comment by mikeslowik** [comment]
It seems that bringing the firmware to 3.2(3d) should resolve the issue as it seems to be triggered by old TLS versions being blocked by default these days:

https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/release/notes/CiscoUCSManager-RN-3-2.html#Cisco_Reference.dita_65063a22-9e64-45c3-85b6-4b9bc556d9e7

Nevertheless in my opinion specifying port 80 implies http - or at least it should - and hence a non-secure connection. Forcing this behaviour should not be a big challenge, so stay tuned for the updates.

**Comment by mikeslowik** [comment]
Hi Stuart,

Now you should be able to connect to CIMC over http - let me know if this is a valid workaround for your issue.

**Comment by wipeoutstu** [comment]
Hi.
Thanks for the update, i'll try it again and let you know :)

**Comment by wipeoutstu** [comment]
Hi Sorry for the delay in testing, had a number of things going off over xmas, new year and jan.

Ive installed the latest version (docker build) and tried it again after a firmware update.

Im getting the connection refused error again:

2022-01-22 16:00:55 UTC [INFO] Connecting to CIMC IP: 10.10.10.102 using account: admin
2022-01-22 16:00:55 UTC [ERROR] Error when trying to login to CIMC: "urlopen error [Errno 111] Connection refused"


I guess the M3's just dont support the process :(

**Comment by mikeslowik** [comment]
Hi Stuart,

Perhaps I wasn't precise enough - if you want to connect over http instead of https you have to specify port 80 in CIMC field, so in your example: 10.10.10.102:80. In all other cases - i.e. no port provided or port other than 80 - it will try to connect over https, which clearly does not work on your M3s with this old firmware.

Give it one more try and let me know if it worked with this workaround, please.

**Comment by wipeoutstu** [comment]
HI.
Sorry, i pasted the wrong attempt in, there were several!  I tried it both ways:

2022-01-22 16:13:58 UTC [INFO] Connecting to CIMC IP: 10.10.10.102:80 using account: admin
2022-01-22 16:13:58 UTC [ERROR] Error when trying to login to CIMC: "urlopen error [Errno 111] Connection refused"

2022-01-22 16:00:55 UTC [INFO] Connecting to CIMC IP: 10.10.10.102 using account: admin
2022-01-22 16:00:55 UTC [ERROR] Error when trying to login to CIMC: "urlopen error [Errno 111] Connection refused"

Same error :(

**Comment by mikeslowik** [comment]
OK. Interestingly enough - this is a different error for the original one, as previously it was clearly referring to SSL.
I saw a similar error when I was working on another tool that we use for upgrading firmware and setting CIMC/BIOS settings. The full message was referring to older Python and Openssl versions:

imc - ERROR - Please make sure Python version >=2.7.9 and Openssl verion >= 1.0.1 are installed for >= CIMC 3.0
imc - DEBUG - Login to IMC failed: <urlopen error [Errno 111] Connection refused>

That was on C420 M3 running really ancient firmware (1.5(7a)). In your case the firmware isn't that ancient but it is definitely the root cause for CIMC login failures.

I see 2 options for you:
1. Upgrade firmware on your machines and use current Auto Installer version
2. Wait for Auto Installer 2.0 which will support PXE boot installs - although that may require some modifications on network level, depending on your setup

**Comment by wipeoutstu** [comment]
Hi, 
Ive updated to firmware (bundle version) 4.0(1a) and im still not able to install:

2022-01-25 12:40:36 UTC [INFO] Connecting to CIMC IP: 10.10.10.11 using account: admin
2022-01-25 12:40:37 UTC [ERROR] Error when trying to login to CIMC: HTTP Error 404: Not Found

2022-01-25 12:40:51 UTC [INFO] Connecting to CIMC IP: 10.10.10.11:80 using account: admin
2022-01-25 12:40:52 UTC [ERROR] Error when trying to login to CIMC: HTTP Error 403: Forbidden

I'm going to get hold of an M4 blade and try that, see if it's any different. Failing that, ill wait for v2 of the installer.
Thanks for all your efforts.

**Comment by mikeslowik** [comment]
I must admit I have not tested IMC SDK with Cisco blades as I only have standalone UCS models in my test rack, so there is a chance blades are not supported in which case PXE boot installation is the only option. 

Could you please login to CIMC and check what it says in PID field? On UCS-C machines is it on Summary page, right next to Product Name and Serial Number. For example on my C480 M5 it says UCSC-C480-M5.

**Comment by wipeoutstu** [comment]
Ah
I assumed it was tested with UCS manager connected devices.
Standalone servers wouldn't be connecting through UCS Manager, which blades do. The CIMC's are controlled and managed  via UCS Manager and KVM config is applied via UCSM.

The PN is
UCSB-B200-M3

**Comment by mikeslowik** [comment]
OK, so that's probably it - IMC SDK validates server model based on one of these conditions:

        valid_model_prefixes = ["UCSC", "UCS-E", "UCSS", "HX"]
        valid_models = ["R460-4640810", "C260-BASE-2646"]

At least we have a clear situation - for Cisco blades the only option is to use PXE boot, because we cannot mount custom ISO using CIMC API. So stay tuned and wait for v2.0 :)

**Comment by wipeoutstu** [comment]
Thats a pity
PXE booting will be no faster / or more automated as additional environmental config is needed for the PXE to work.
I was hoping to use the solution for greenfield/new installs for customers to speed up deployment, and 99% of the deployments are blades or UCSM integrated.
Thanks anyway

**Comment by GhentGunn** [comment]
@wipeoutstu , The new release has been posted which supports installation via PXE boot.
