### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by heavytb** [CiscoDevNet/esxi-auto-installer#34]
I am geting  Error when trying to login to CIMC: "urlopen error [SSL] internal error (_ssl.c:1131)" when I start a job. The target servers are B200 M6

**Comment by GhentGunn** [comment]
Sounds like this could be related to the version of SSL used and the python libraries.
What CIMC firmware version is your B200 M6 on?
Can you confirm which version of TLS the CIMC is using?
This issue looks similar to this issue: https://github.com/keenlabs/KeenClient-Python/issues/161
and this blog: https://clay-atlas.com/us/blog/2021/09/26/python-en-urllib-error-ssl-certificate/

**Comment by GhentGunn** [comment]
Doing a little more research, they maybe two issues involved here:
1) The TLS/SSL version may not be compatible, this may happen if you have a really old firmware version. But since it's an M6 blade I wouldn't think this is the case.
To try and avoid this issue entirely, you can add port 80 to the CIMC IP address like so: 192.168.0.100:80, this will bypass the SSL issue entirely.
2) The second issue is that the Python IMC SDK does not support the B-Series blades. So even after you work around the TLS issue, you will just get another issue because the platform is not supported.

For more details, see issue: https://github.com/CiscoDevNet/esxi-auto-installer/issues/26

We are actively working on a version 2 of the ESXi AutoInstaller which will include the ability to install via PXE Boot. Since this method does not use the Python IMC SDK, it can be used for B-Series blades, or any platform that supports PXE.

**Comment by GhentGunn** [comment]
No replies, so I'm closing this issue. The new PXE branch was open today, we'll merge it into the main branch as soon as it's stable.
Once it's merged to the main branch, you can download the update and try to install using the DHCP method.
